-- Enable Row-Level Security on all public tables.
-- The app uses Prisma (direct postgres connection) which bypasses RLS as db owner.
-- This blocks unauthorized access via Supabase's PostgREST API (anon/authenticated roles).

ALTER TABLE "SchoolYear" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Class" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Staff" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Student" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SiblingLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentEnrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GradeRetention" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WaitlistEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WaitlistVisit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Evaluation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyGroupPlacement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RetentionWatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TutoringAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BehaviorIncident" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BehaviorLevelChange" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ParentContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeeSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeeAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Observation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeaveRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimeClockEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffAttendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Trimestre" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportCard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportCardEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Transcript" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimeSlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimetableEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SchoolCalendarEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyDataSubmission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Suggestion" ENABLE ROW LEVEL SECURITY;
